### ISSUE TITLE
does not work on toaster

### ISSUE THREAD

**Issue by liammross** [DillyzThe1/StopTimeMod#1]
I have the Die-Cast 2-Slice Smart Toaster, and when I boot up among us nothing happens. Please help

(This is a joke btw if it is not clear dillyz.) (I am PopCat on discord that records with cheep)
![lel](https://user-images.githubusercontent.com/74442727/108633902-bdb36b00-742b-11eb-9cae-4a69b1b3bbc2.jpg)

**Comment by DillyzThe1** [comment]
I'm so sorry! I completely forgot to optimize the entire mod for use with a toaster!
Plwase give me 3.8 thousand years to patch the mod for toasters, as it is the first step to the mobile version.

But for real, I actually started laughing when i saw this the ONE TIME I read an e-mail notification.

**Comment by DillyzThe1** [comment]
just noticed a typo but cant edit AAAAAAA

**Comment by BG-Music** [comment]
> I have the Die-Cast 2-Slice Smart Toaster, and when I boot up among us nothing happens. Please help
> 
> (This is a joke btw if it is not clear dillyz.) (I am PopCat on discord that records with cheep)
> ![lel](https://user-images.githubusercontent.com/74442727/108633902-bdb36b00-742b-11eb-9cae-4a69b1b3bbc2.jpg)

Does not work for mine either

**Comment by liammross** [comment]
> > I have the Die-Cast 2-Slice Smart Toaster, and when I boot up among us nothing happens. Please help
> > (This is a joke btw if it is not clear dillyz.) (I am PopCat on discord that records with cheep)
> > ![lel](https://user-images.githubusercontent.com/74442727/108633902-bdb36b00-742b-11eb-9cae-4a69b1b3bbc2.jpg)
> 
> Does not work for mine either

yes he said it will be fixed in 3.8k years
not that long

**Comment by liammross** [comment]
so I think I can close this
