### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by Oktav99a** [DillyzThe1/StopTimeMod#2]
There are multiple problems among us in this mod
Impostor movement looks really bad from the crewmates prespective, they seem like they are teleporting. That is because, if you have a lower move speed than someone else, they look like they are teleporting.
You can *report*, *do tasks* and other stuff while frozen, because all it does is set the crew move speed to 0. Socksfor1 disables the controls entirely.

Also, the mod discord server invite doesn't work for me

**Comment by DillyzThe1** [comment]
Hello! I have fixed all of these in-game problems today and will make sure the invite does work properly.
Thanks for telling me :)
